services:
  mysql:
    image: 'mysql:8.4.10'
    container_name: 'tinyurl-mysql'
    environment:
      - 'MYSQL_DATABASE=tinyurl'
      - 'MYSQL_USER=tinyurl'
      - 'MYSQL_PASSWORD=tinyurl'
      - 'MYSQL_ROOT_PASSWORD=tinyurl-root'
    ports:
      - '3306:3306'
    volumes:
      - 'mysql-data:/var/lib/mysql'
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1G
        reservations:
          memory: 512M
  grafana-lgtm:
    image: 'grafana/otel-lgtm:0.29.2'
    container_name: 'tinyurl-grafana-lgtm'
    ports:
      - '3000:3000'
      - '4317:4317'
      - '4318:4318'
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
        reservations:
          memory: 512M
  redis:
    image: 'redis:8.2-alpine'
    container_name: 'tinyurl-redis'
    command: 'redis-server --maxmemory 400mb --maxmemory-policy allkeys-lru'
    ports:
      - '6379:6379'
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          memory: 256M
  zookeeper:
    image: 'zookeeper:3.9.4'
    container_name: 'tinyurl-zookeeper'
    ports:
      - '2181:2181'
    volumes:
      - 'zookeeper-data:/data'
      - 'zookeeper-datalog:/datalog'
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          memory: 256M

volumes:
  mysql-data:
  zookeeper-data:
  zookeeper-datalog:
