spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.hugo.tinyurl.infra.messaging

app:
  click-event:
    async:
      core-pool-size: 4
      max-pool-size: 8
      queue-capacity: 500
    kafka:
      topic: click-events
      consumer-group: click-event-consumer
      partitions: 1
      concurrency: 1
