spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    template:
      observation-enabled: true
    listener:
      observation-enabled: true
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      auto-offset-reset: earliest
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.hugo.tinyurl.clickevent.infra.messaging

app:
  click-event:
    async:
      core-pool-size: 4
      max-pool-size: 8
      queue-capacity: 500
    kafka:
      topic: click-events
      consumer-group: click-event-consumer
      partitions: 1
      concurrency: 1
      retry:
        initial-interval-ms: 1000
        max-interval-ms: 5000
        max-elapsed-ms: 15000
